from pathlib import Path
import sqlite3,json,hashlib,os
from urllib.parse import quote
root=Path(__file__).resolve().parents[1];out=root/'private/ocr-history-db';db=sqlite3.connect(out/'ocr-20260924.sqlite3');db.row_factory=sqlite3.Row
records=[];seen=set();skipped=0
for r in db.execute("SELECT * FROM scores WHERE field IN ('rec_score','score','ocr_score') ORDER BY CASE WHEN field='rec_score' THEN 0 ELSE 1 END,id"):
 source=r['source_path'];pointer=r['json_pointer'];ctx=json.loads(r['context_json'])
 if 'initial-column-error' in source or '/trace/' in pointer:continue
 if Path(source).name not in ['results.json','extra-results.json'] and r['field']!='rec_score' and not any(x in Path(source).name for x in ['repeat-','adaptive-','underscore-']):continue
 inp=ctx.get('input_path',ctx.get('input'))
 if '/otsu/' in pointer:
  payload=json.loads(db.execute('SELECT content FROM artifacts WHERE path=?',(source,)).fetchone()[0]);idx=int(pointer.split('/')[1]);inp=payload[idx].get('variant_input')
 if not inp or r['text'] is None:skipped+=1;continue
 image=root/Path(inp.replace('\\','/'))
 if not image.is_file() or image.suffix.lower() not in ['.png','.jpg','.jpeg']:skipped+=1;continue
 # This view uses actual OCR input crops, not reconstructed or teacher-corrected images.
 key=(r['experiment'],str(image),r['text'],r['score'])
 if key in seen:continue
 seen.add(key)
 records.append({'experiment':r['experiment'],'image':quote(os.path.relpath(image,out).replace('\\','/'),safe='/:'),'text':r['text'],'score':r['score']})
records.sort(key=lambda x:(0 if x['experiment']=='choice-auto-location-20260924' else 1,x['experiment']))
payload=json.dumps(records,ensure_ascii=False).replace('<','\\u003c')
page=r'''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>학생 필기 · OCR 결과</title><style>*{box-sizing:border-box}body{margin:0;background:#f4f5f7;color:#202a38;font-family:Malgun Gothic,Segoe UI,sans-serif}main{max-width:1150px;margin:auto;padding:32px 24px}h1{font-size:26px;margin:0 0 22px}header{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:18px}select,input,button{font:inherit;border:1px solid #cbd2dc;border-radius:7px;padding:10px;background:white}input{width:230px}table{width:100%;border-collapse:collapse;background:#fff;table-layout:fixed}th{text-align:left;padding:16px;background:#e8edf3;font-size:15px}td{border-bottom:1px solid #e3e7ed;padding:16px;vertical-align:middle}th:first-child{width:48%}th:nth-child(2){width:35%}th:last-child{width:17%}td img{max-width:100%;max-height:155px;object-fit:contain;cursor:zoom-in;display:block}td:nth-child(2){font-size:23px;word-break:break-word;white-space:pre-wrap}td:last-child{font-size:23px;font-variant-numeric:tabular-nums}footer{display:flex;justify-content:space-between;align-items:center;margin-top:18px}.note{font-size:13px;color:#677382;margin:16px 0}dialog{max-width:94vw;max-height:94vh;border:0;border-radius:10px;padding:20px}dialog img{max-width:85vw;max-height:78vh;display:block}dialog::backdrop{background:#0009}@media(max-width:650px){main{padding:15px 8px}td,th{padding:9px}td:nth-child(2),td:last-child{font-size:17px}}</style><main><h1>학생 필기와 OCR 결과</h1><header><select id="experiment" aria-label="시험 선택"><option value="">전체 시험</option></select><input id="search" placeholder="인식한 내용 검색" aria-label="인식 내용 검색"></header><table><thead><tr><th>OCR이 본 것 · 학생 필기</th><th>OCR이 인식한 것</th><th>OCR 점수</th></tr></thead><tbody id="rows"></tbody></table><footer><button id="prev">이전</button><span id="count"></span><button id="next">다음</button></footer><p class="note">이미지를 누르면 크게 볼 수 있습니다. 점수는 모델 원점수이며 정답 확률은 아닙니다. 실제 입력 조각과 연결된 기록만 표시합니다.</p></main><dialog id="zoom"><button id="close">닫기</button><img alt="OCR이 본 학생 필기 확대"></dialog><script id="data" type="application/json">PAYLOAD</script><script>
const data=JSON.parse(document.getElementById('data').textContent),exp=document.getElementById('experiment'),search=document.getElementById('search'),body=document.getElementById('rows'),zoom=document.getElementById('zoom');let page=0;const labels={'choice-auto-location-20260924':'객관식 · 자동 위치 탐색','choice-marks-20260924':'객관식 · 선지 직접 표시','mixed-ocr-20260924':'객관식·서술형 · 수동 영역','mixed-reference-ocr-20260924':'객관식·서술형 · 원본 비교','page2-textline-ocr-20260924':'비교급 · 인쇄 줄 경계','page2-upper-ocr-20260924':'비교급 · 위쪽 경계','page2-ocr-20260924':'비교급 · 첫 시험','scope-compare-20260924':'객관식·주관식 · 전처리 비교','page2-followup-ocr-20260924':'비교급 · 반복·경계 시험','difference-ocr-20260924':'첫 페이지 · 원본 차이','underline-ocr-20260924':'첫 페이지 · 밑줄 전체','underline-end-ocr-20260924':'첫 페이지 · 밑줄 끝 경계','better-boundary-20260924':'첫 페이지 · better 경계 수정'};
for(const name of [...new Set(data.map(x=>x.experiment))]){const o=document.createElement('option');o.value=name;o.textContent=labels[name]||name;exp.append(o)}
function render(){const a=data.filter(x=>(!exp.value||x.experiment===exp.value)&&x.text.toLowerCase().includes(search.value.toLowerCase()));page=Math.max(0,Math.min(page,Math.max(0,Math.ceil(a.length/30)-1)));body.replaceChildren();for(const x of a.slice(page*30,page*30+30)){const tr=document.createElement('tr'),im=document.createElement('img');im.src=x.image;im.alt='OCR 입력 필기';im.loading='lazy';im.onclick=()=>{zoom.querySelector('img').src=x.image;zoom.showModal()};const imageCell=document.createElement('td');imageCell.append(im);const textCell=document.createElement('td');textCell.textContent=x.text||'(읽은 내용 없음)';const scoreCell=document.createElement('td');scoreCell.textContent=x.score.toFixed(4);scoreCell.title=String(x.score);tr.append(imageCell,textCell,scoreCell);body.append(tr)}document.getElementById('count').textContent=a.length+'개 · '+(page+1)+' / '+Math.max(1,Math.ceil(a.length/30))+'쪽';document.getElementById('prev').disabled=page===0;document.getElementById('next').disabled=(page+1)*30>=a.length}
for(const el of [exp,search])el.oninput=()=>{page=0;render()};document.getElementById('prev').onclick=()=>{page--;render()};document.getElementById('next').onclick=()=>{page++;render()};document.getElementById('close').onclick=()=>zoom.close();render();
</script></html>'''
index=out/'index.html'
if index.exists() and not (out/'detailed-index.html').exists():(out/'detailed-index.html').write_bytes(index.read_bytes())
index.write_text(page.replace('PAYLOAD',payload),encoding='utf-8')
(out/'simple-view-manifest.json').write_text(json.dumps({'rows':len(records),'groups':len(set(r['experiment'] for r in records)),'unlinked_skipped':skipped,'notes':'No database mutation. Derived score-only records and whole-page arrays excluded from crop view. Repeated report copies deduplicated, not distinct experimental repeats.'},indent=2),encoding='utf-8')
print(len(records),'image-linked records')
